import 'package:child_missing_app1/wraper.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // auto-generated by FlutterFire CLI

import 'screens/onboarding_screen.dart';
import 'screens/auth_screen.dart';
import 'screens/home_screen.dart';
import 'screens/report_missing_screen.dart';
import 'screens/found_child_screen.dart';
import 'screens/face_match_screen.dart';
import 'screens/profile_screen.dart';
import 'screens/notification_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        appBarTheme: AppBarTheme(
          iconTheme: const IconThemeData(
              color: Colors.white), // Set the icon color to white globally
        ),
      ),
      debugShowCheckedModeBanner: false,
      title: 'Missing Child Finder',
      initialRoute: '/',
      routes: {
        '/': (context) => const Wrapper(),
        // '/': (context) => const SplashScreen(),
        '/onboarding': (context) => const OnboardingScreen(),
        '/login': (context) => AuthScreen(),
        '/home': (context) => HomeScreen(),
        '/report_missing': (context) => const ReportMissingScreen(),
        '/found_child': (context) => const FoundChildScreen(),
        '/face-match': (context) => const FaceMatchScreen(),
        '/profile': (context) => const ProfileScreen(),
        '/notifications': (context) => const NotificationScreen(),
      },
    );
  }
}
